### ISSUE TITLE
The ; command can't handle values bigger then 255

### ISSUE THREAD

**Issue by Etoplay** [mbuettner/hexagony#2]
When I execute the ; command on values bigger than 255 or lower than 0 I get the message "in `chr': 256 out of char range (RangeError)".

I would expect either unicode (not sure what negative values would mean) or the character modulo 256.
A third possibility would be to write into the doc that values outside of [0,255] can't be handled.

I would prefer modulo 256 because that would make it easier to output a linebreak with M 8 ;

**Comment by m-ender** [comment]
I'll give this some thought, but modulo 256 sounds good.

**Comment by Timwi** [comment]
Well, right now the documentation implies that the `;` command outputs _characters_. Therefore, the choices are:
- Change it so that it says _bytes_ instead. Then you can’t output non-ASCII characters except by implementing a UTF-8 encoder in Hexagony. Then you still have to decide whether values outside the range of a byte should be moduloed or throw an error.
- Change it so that it actually outputs any Unicode character. Then the interpreter has to assume an output encoding, meaning you can no longer use Hexagony to output any byte stream.

**Comment by m-ender** [comment]
I've gone ahead with this change and made the I/O work with bytes instead of characters. Output is taken modulo 256 as suggested.
